### ISSUE TITLE
contact Image on mobile

### ISSUE THREAD

**Issue by brucewf** [oscunimelb/CustomerPortal#10]
https://studentadmin-unimelb--tst1.custhelp.com/dav/euf/assets/themes/mobile/images
contact.png
icon showing below other icons on mobile   http://studentadmin-unimelb--tst1.custhelp.com/app

**Comment by jeremybean** [comment]
I think that the best solution might just be to drop the usage of the image altogether on the Mobile pages.

**Comment by brucewf** [comment]
I agree, drop the icon.

**Comment by jeremybean** [comment]
Not using this image.
